{
 "title": "VPN Dev",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Load avg",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{host=\"10.10.10.2\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{host=\"10.10.10.2\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Net",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"eth0\",host=\"10.10.10.2\"}[2m])*8",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "HDD Root",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\",host=\"10.10.10.2\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "HDD Home",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/home\",host=\"10.10.10.2\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Teams",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(rate(node_network_receive_bytes_total{device=~\"team.+\",host=\"10.10.10.2\"}[2m])*8 > 0)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Top TX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"team.+\",host=\"10.10.10.2\"}[2m]) > 100",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "HDD Root IO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"md1\",host=\"10.10.10.2\"}[2m])",
     "legendFormat": "r"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"md1\",host=\"10.10.10.2\"}[2m])  ",
     "legendFormat": "w"
    }
   ]
  },
  {
   "title": "HDD Home IO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"md2\",host=\"10.10.10.2\"}[2m])",
     "legendFormat": "{{hostname}} r"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"md2\",host=\"10.10.10.2\"}[2m])",
     "legendFormat": "{{hostname}} w"
    }
   ]
  },
  {
   "title": "Top RX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"team.+\",host=\"10.10.10.2\"}[2m]) > 0",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}