version: "3"

services:
  postgres:
    image: postgres:13.2-alpine
    restart: always
    env_file:
      - variables.env
    ports:
      - 5432:5432

  trackbattle:
    build: .
    restart: on-failure
    env_file:
      - variables.env
    depends_on:
      - postgres
    ports:
      - 31337:31337

