services:
  app:
    build: .
    ports:
      - "5051:8080"
    restart: always
    volumes:
      - "${HOME}/.m2:/root/.m2"
    depends_on:
      - postgres
    stop_grace_period: 3s
    mem_limit: 1G
    pids_limit: 50

  postgres:
    image: postgres:13.2-alpine
    restart: always
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 100
    volumes:
        - data:/var/lib/postgresql/data/
        - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres

volumes:
    data:
    dependencies:
