version: '3.3'
services:
  white_album:
    image: white_album
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8001:8001"
    volumes:
      - ./data:/app/data
    restart: unless-stopped