version: '3.3'
services:
  white_album:
    image: white_album
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "1234:1234"
    volumes:
      - data:/app/data

    restart: unless-stopped

volumes:
    data: