services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    stop_grace_period: 3s
#    mem_limit: 4G
#    memswap_limit: 1G # we don't use swap, but why not
#    pids_limit: 10

  postgres:
    image: postgres:13.1-alpine
    restart: always
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 100
    volumes:
        - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
