version: '2.4'

services:
  spotiflag:
    container_name: spotiflag
    build: spotiflag
    restart: always
    volumes:
      - songs:/tmp/songs/
      - spotiflag:/tmp/spotiflag/
    stop_grace_period: 3s
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 1024
    ulimits: 
      nofile:
        soft: 8192
        hard: 8192

  web:
    container_name: spotiflag_web
    build: web
    restart: always
    volumes:
      - spotiflag:/tmp/spotiflag/
    environment:
      - REDIS_ADDRESS=redis
      - SPOTIFLAG_SOCKET=/tmp/spotiflag/spotiflag.sock
      - EXPIRE=600 # 10 minutes
    ports:
      - 17171:8000
    depends_on:
      - redis
      - spotiflag
    stop_grace_period: 3s
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 512
    ulimits: 
      nofile:
        soft: 8192
        hard: 8192

  redis:
    container_name: spotiflag_redis
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 128

volumes:
  spotiflag:
  songs:
  redis:
