---
- hosts: all
  become: yes

  gather_facts: no
  pre_tasks:
    - name: 'Ensure tmp exists'
      raw: sudo mkdir -p /run/ansible_tmp/
      changed_when: False
    - name: 'Ensure tmp dir rights'
      raw: sudo chmod a+rwx /run/ansible_tmp/
      changed_when: False

  roles:
    - { role: base_image, tags: [base] }
    - install_go
    - bay_cloud_config
    - { role: nginx, tags: [front] }
    - { role: service, service_name: demo, tags: [demo] }
    