---
- hosts: all
  become: yes

  gather_facts: no
  pre_tasks:
    - name: 'Ensure tmp exists'
      raw: sudo mkdir -p /run/ansible_tmp/
      changed_when: False
    - name: 'Ensure tmp dir rights'
      raw: sudo chmod a+rwx /run/ansible_tmp/
      changed_when: False

  roles:
    - { role: systemd_base_image, tags: [base] }
    - bay_cloud_config
    - { role: systemd_service, service_name: studio, tags: [studio] }
    