---
- name: create docker conf dir
  file:
    path: /etc/docker
    state: directory

- name: create docker lib dir
  file:
    path: /home/docker-lib/
    state: directory

- name: configure docker dir before install
  copy:
    src: docker-daemon.json
    dest: /etc/docker/daemon.json
    mode: 0755
    owner: root

- name: Install utils
  apt:
    name:
      - apt-transport-https
      - mc
      - vim
      - htop
      - rsync
      - tmux
      - silversearcher-ag
      - docker.io
      - docker-compose
      - zerofree # for making smaller image size
      - virtualbox-guest-utils
    state: latest
    install_recommends: false
    update_cache: yes

- name: Fix base image
  file: path='{{ item }}' state=absent
  with_items:
    - /ructf-banner.txt
    - /etc/systemd/system/ructf@.service

- name: Remove Ubuntu MOTD
  file: path='/etc/update-motd.d/{{ item }}' state=absent
  with_items:
    - 50-landscape-sysinfo
    - 50-motd-news
    - 80-esm
    - 80-livepatch
    - 85-fwupd
    - 88-esm-announce
    - 90-updates-available
    - 91-contract-ua-esm-status
    - 91-release-upgrade
    - 92-unattended-upgrades
    - 95-hwe-eol
    - 97-overlayroot
    - 98-fsck-at-reboot
    - 98-reboot-required

- name: Copy banner
  copy:
    src: ructf-banner.txt
    dest: /ructf-banner.txt
    mode: 0644

- name: Copy MOTD
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: root
  with_items:
    - {src: "00-header", dest: "/etc/update-motd.d/00-header"}
    - {src: "10-help-text", dest: "/etc/update-motd.d/10-help-text"}
