
name: Check spotiflag
on:
  push:
    branches:
      - main
    paths:
      - 'services/spotiflag/**'
      - 'checkers/spotiflag/**'
  workflow_dispatch:
    inputs:
      cleanup_before_deploy:
        description: 'Stops and fully removes service (with volumes!) before deploying again. Type "yes" to do it.'
        required: false
        default: "no"

jobs:
  check_spotiflag:
    name: Check spotiflag
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Run prebuilt hook
      run: if [ -f services/spotiflag/before_image_build.sh ]; then (cd ./services/spotiflag && ./before_image_build.sh); fi

    - name: Setup spotiflag
      run: (cd ./services/spotiflag && docker-compose pull && docker-compose build && docker-compose up --build -d)

    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5

    - name: Setup checker libraries
      run: if [ -f checkers/spotiflag/requirements.txt ]; then python -m pip install -r checkers/spotiflag/requirements.txt; fi

    - name: Test checker on service
      run: checkers/spotiflag/checker.py TEST 127.0.0.1

  update_spotiflag:
    name: Deploy service using ansible to first teams
    needs: check_spotiflag
    runs-on: ubuntu-18.04
    if: ${{ false }} # disable on game just in case

    steps:
    - name: install ansible
      run: sudo apt-get install -y ansible

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: change permission for ssh key
      run: chmod 0600 ./vuln_image/keys/id_rsa

    - name: Run prebuilt hook
      run: if [ -f services/spotiflag/before_image_build.sh ]; then (cd ./services/spotiflag && ./before_image_build.sh); fi

    - name: stop spotiflag, destroy volumes and cleanup service before fresh deploy
      if: ${{ github.event.inputs.cleanup_before_deploy == 'yes' }}
      run: ./vuln_image/cleanup_first_ten_teams.sh spotiflag

    - name: try to deploy spotiflag
      run: ./vuln_image/update_first_ten_teams.sh spotiflag

